### ISSUE TITLE
Battery Drain on Android 10 MIUI 12

### ISSUE THREAD

**Issue by DotIN13** [rurirei/Kitsunebi#9]
### what is your environment info (mobile system, app version, etc)?
MIX3 Android 10 MIUI 12 Kitsunebi-xray-1.3.0
 ### what is your problem meet?
Battery drain, like 400mAh in 1.5h

 ### paste your configuration here
 ```json
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 10809,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "",
                        "port": 6516,
                        "users": [
                            {
                                "id": "",
                                "flow": "xtls-rprx-direct",
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "serverName": ""
                }
            }
        }
    ]
}
 ```

**Comment by rurirei** [comment]
battery usage of VPN services tells you battery consumptions more. if Kitsunebi consumes too much, 20%+/hour for example?

**Comment by DotIN13** [comment]
V2rayNG consumed 211 mAh as of 19% in 16 hours, whilst kitsunebi consumed 420mAh in approximately 3 hours.

I see that you released a newer version, will get back to you on the consumption of the new ver.

**Comment by rurirei** [comment]
log needed. with log level `debug` in your configuration and app settings.
```cmd
adb logcat -s io.github.rurirei.kitsunebi Go GoLog ActivityManager
```

**Comment by DotIN13** [comment]
Will do the logcat when I have time.

**Comment by DotIN13** [comment]
Long overdue logs: https://pastebin.com/hD6bh6i6

**Comment by DotIN13** [comment]
Not sure if this is the underlying exception to the drain?
```log
03-04 15:47:55.756  1585  1711 I ActivityManager: Waited long enough for: ServiceRecord{13d635 u0 com.coolapk.market/com.ss.android.socialbase.downloader.notification.DownloadNotificationService}
03-04 15:47:58.660  1585  1695 W ActivityManager: Exception when unbinding service io.github.rurirei.kitsunebi/io.github.rurirei.v2rayng.service.V2RayVpnService
03-04 15:47:58.660  1585  1695 W ActivityManager: android.os.DeadObjectException
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1627)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3399)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:2051)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:14457)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1789)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.connectivity.Vpn$2.interfaceRemoved(Vpn.java:1476)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.NetworkManagementService.lambda$notifyInterfaceRemoved$3(NetworkManagementService.java:390)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.-$$Lambda$NetworkManagementService$FsR_UD5xfj4hgrwGdX74wq881Bk.sendCallback(Unknown Source:2)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.NetworkManagementService.invokeForAllObservers(NetworkManagementService.java:351)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.NetworkManagementService.notifyInterfaceRemoved(NetworkManagementService.java:390)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.NetworkManagementService.access$600(NetworkManagementService.java:122)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.NetworkManagementService$NetdUnsolicitedEventListener.lambda$onInterfaceRemoved$6$NetworkManagementService$NetdUnsolicitedEventListener(NetworkManagementService.java:740)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.-$$Lambda$NetworkManagementService$NetdUnsolicitedEventListener$h2iz-IbnHpQ97mlJ7G62W2mmanw.run(Unknown Source:4)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.os.Handler.handleCallback(Handler.java:883)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.os.Looper.loop(Looper.java:224)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-04 15:47:58.660  1585  1695 W ActivityManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:45)
03-04 15:47:58.708  1585  4310 I ActivityManager: Process io.github.rurirei.kitsunebi (pid 28606) has died: fore TOP 
```

**Comment by rurirei** [comment]
seems no problem. do you try other Android variant than MIUI?

**Comment by DotIN13** [comment]
> seems no problem. do you try other Android variant than MIUI?

No I do not. But what did interest me was that according to the battery report, v2rayNG only used minutes of CPU in a whole day, while kitsunebi used CPU every single minute it was on.

**Comment by rurirei** [comment]
please do log on both v2rayNG and Kitsunebi.

**Comment by DotIN13** [comment]
Okey will do.

**Comment by DotIN13** [comment]
Sorry my previous log didn't have log level correctly set, here's the new one with log level debug: https://wannaexpresso.lanzous.com/i9XxLmhtbqf

It seemed there appeared a horde of the following error:
```
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
```

**Comment by DotIN13** [comment]
The log for V2RayNG: https://pastebin.com/VWwVV8Y5

Looks like there's also a huge amount of `context canceled` error. Very confusing.

**Comment by rurirei** [comment]
no idea.

do check usage of your xray config.
```golang

03-04 20:37:58.497 11562 11666 I GoLog   : [Info] proxy/vless/outbound: tunneling request to udp:216.58.194.162:443 via tcp:___SERVER HOSTNAME DELETED___:6516
03-04 20:37:58.498 11562 11703 I GoLog   : [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: xtls-rprx-direct stopped UDP/443
```

**Comment by DotIN13** [comment]
> no idea.
> 
> do check usage of your xray config.
> 
> ```go
> 03-04 20:37:58.497 11562 11666 I GoLog   : [Info] proxy/vless/outbound: tunneling request to udp:216.58.194.162:443 via tcp:___SERVER HOSTNAME DELETED___:6516
> 03-04 20:37:58.498 11562 11703 I GoLog   : [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: xtls-rprx-direct stopped UDP/443
> ```

Seems this error shows up on both V2rayNG and Kitsunebi, so I am not sure if this could be the problem. Or it could be that I was using per-app proxy with V2rayNG so less connections got proxied which resulted in less battery consumption.

I think we can close this for now and I'll be keeping both applications in my phone, will get you updated if I had any different experience.

**Comment by DotIN13** [comment]
After using V2RayNG for a while longer, I realized that if I turn off per-app tunnelling, the battery drain goes up dramatically. So I would conclude that the drain was caused by loading all traffic thru the tunnelling application.
